// packages/integrations/solid/src/store.ts
import { createEffect, createSignal, onCleanup } from 'solid-js';
import { get } from '@astrojs/store';
import type { Readable } from '@astrojs/store';

export function useStore<T>(readable: Readable<T>) {
    const [state, setState] = createSignal(get(readable));

    createEffect(() => {
        onCleanup(readable.subscribe(setState as (value: T) => void));
    });

    return state;
}

// packages/integrations/react/src/store.ts
import { useEffect, useState } from 'react';
import { get } from '@astrojs/store';
import type { Readable } from '@astrojs/store';

export function useStore<T>(readable: Readable<T>) {
    const [state, setState] = useState(get(readable));

    useEffect(() => {
        return readable.subscribe(setState);
    }, []);

    return state;
}
