// examples/portfolio/src/components/Footer/index.jsx
import { h } from 'preact';
import Styles from './styles.module.scss';

function Footer() {
  return (
    <footer className={Styles.footer}>
      &copy; {new Date().getFullYear()} Jeanine White
      <small className={Styles.byline}>🚀 Built by Astro</small>
    </footer>
  );
}
export default Footer;

// examples/portfolio-svelte/src/components/Footer.svelte
<script>
    export let name = "Jeanine White";
</script>

<footer>
    &copy; {new Date().getFullYear()} {name}
    <small>🚀 Built with Astro</small>
</footer>

<style>
    footer {
        text-align: center;
        padding: 8rem 2rem 4rem;
    }

    small {
        display: block;
        margin-top: 1rem;
        color: var(--t-subdue);
        font-size: var(--f-d2);
        text-transform: uppercase;
    }
</style>
