// examples/framework-react/src/components/Counter.tsx
import React from 'react';
import './Counter.css';

export default function Counter({
	children,
	count: initialCount,
}: {
	children: React.JSX.Element;
	count: number;
}) {
	const [count, setCount] = React.useState(initialCount);
	const add = () => setCount((i) => i + 1);
	const subtract = () => setCount((i) => i - 1);

	return (
		<>
			<div className="counter">
				<button onClick={subtract}>-</button>
				<pre>{count}</pre>
				<button onClick={add}>+</button>
			</div>
			<div className="counter-message">{children}</div>
		</>
	);
}

// src/components/Counter.tsx
import { createSignal, type JSX } from 'solid-js';
import './Counter.css';

export default function Counter(props: { children?: JSX.Element }) {
	const [count, setCount] = createSignal(0);
	const add = () => setCount(count() + 1);
	const subtract = () => setCount(count() - 1);

	return (
		<>
			<div class="counter">
				<button onClick={subtract}>-</button>
				<pre>{count()}</pre>
				<button onClick={add}>+</button>
			</div>
			<div class="counter-message">{props.children}</div>
		</>
	);
}
